version: '2'

services:
  kong-admin:
    container_name: kong-admin
    image: pantsel/konga
    ports:
      - 1337:1337
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=db
      - DB_USER=kong
      - DB_DATABASE=konga_db
      - KONGA_HOOK_TIMEOUT=120000
      - NODE_ENV=production
    depends_on:
      - kong
    volumes:
      - .konga:/var/lib/postgresql/data
    networks:
      - kong-network
  kong:
    container_name: kong
    image: kong:latest
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    volumes:
      - .data:/var/lib/postgresql/data
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=db
      - KONG_CASSANDRA_CONTACT_POINTS=db
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stdout
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    depends_on:
      - db
    networks:
      - kong-network
  db:
    container_name: kong_database
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    networks:
      - kong-network
networks:
  kong-network:
    driver: bridge